language: node_js
node_js:
    - "10.0"

script:
    - echo "Deploying catalyst app!"
install:
    - npm install -g zcatalyst-cli
after_success:
    - ls && cd Multilevel-Ballbrick-Game && catalyst deploy --token $CATALYST_AUTH_TOKEN --project $CATALYST_PROJECT_ID
